services:
  minio:
    image: ${IMAGE_NAME:-minio/minio}:${IMAGE_TAG:-latest}
    command: server --address :${SERVER_PORT} --console-address :${CONSOLE_PORT}
    environment:
      MINIO_VOLUMES: ${DATA_PATH}
      MINIO_DOMAIN: ${TRAEFIK_SERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
      MINIO_BROWSER:
      MINIO_SERVER_URL: https://${TRAEFIK_SERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      MINIO_BROWSER_REDIRECT:
      MINIO_BROWSER_REDIRECT_URL: https://${TRAEFIK_CONSOLE_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      MINIO_BROWSER_SESSION_DURATION:
      MINIO_PROMETHEUS_URL:
      MINIO_PROMETHEUS_JOB_ID:
      MINIO_PROMETHEUS_AUTH_TYPE:
    networks:
      minio-net:
      traefik-net:
      metric-net:
    volumes:
      - data-vol:${DATA_PATH}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-node-hostname}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-5m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}

        traefik.http.routers.minio-server.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.minio-server.rule: HostRegexp(`{bucket:[A-z0-9.-]*}${TRAEFIK_SERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.routers.minio-server.service: minio-server
        traefik.http.services.minio-server.loadbalancer.server.port: ${SERVER_PORT}
        traefik.http.services.minio-server.loadbalancer.healthcheck.path: ${TRAEFIK_HEALTHCHECK_PATH}
        traefik.http.services.minio-server.loadbalancer.healthcheck.method: ${TRAEFIK_HEALTHCHECK_METHOD}
        traefik.http.services.minio-server.loadbalancer.healthcheck.interval: ${TRAEFIK_HEALTHCHECK_INTERVAL}
        traefik.http.services.minio-server.loadbalancer.healthcheck.timeout: ${TRAEFIK_HEALTHCHECK_TIMEOUT}

        traefik.http.routers.minio-console.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.minio-console.rule: Host(`${TRAEFIK_CONSOLE_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.routers.minio-console.service: minio-console
        traefik.http.services.minio-console.loadbalancer.server.port: ${CONSOLE_PORT}
        traefik.http.services.minio-console.loadbalancer.healthcheck.path: ${TRAEFIK_HEALTHCHECK_PATH}
        traefik.http.services.minio-console.loadbalancer.healthcheck.method: ${TRAEFIK_HEALTHCHECK_METHOD}
        traefik.http.services.minio-console.loadbalancer.healthcheck.interval: ${TRAEFIK_HEALTHCHECK_INTERVAL}
        traefik.http.services.minio-console.loadbalancer.healthcheck.timeout: ${TRAEFIK_HEALTHCHECK_TIMEOUT}
        traefik.http.services.minio-console.loadbalancer.healthcheck.port: ${SERVER_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-640M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-320M}

networks:
  minio-net:
    name: ${MINIO_NET_NAME:-minio-net}
    driver: ${MINIO_NET_DRIVER:-overlay}
    attachable: ${MINIO_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
