services:
  minio:
    networks:
      gitlab-net:

networks:
  gitlab-net:
    name: ${GITLAB_NET_NAME:-gitlab-net}
    driver: ${GITLAB_NET_DRIVER:-overlay}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}-{{.Node.Hostname}}
