version: '3.5'

services:
  minio:
    image: ${IMAGE_NAME:-minio/minio}:${IMAGE_TAG:-latest}
    command: server /data
    environment:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
    networks:
      minio-net:
      traefik-net:
      gitlab-net:
    volumes:
      - data-vol:${DATA_PATH}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN:-minio}.${PUBLIC_HOSTNAME}
        traefik.backend: minio
        traefik.port: '${PORT:-9000}'
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  minio-net:
    name: ${MINIO_NET_NAME:-minio-net}
    driver: ${MINIO_NET_DRIVER:-overlay}
    attachable: ${MINIO_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  gitlab-net:
    name: ${GITLAB_NET_NAME:-gitlab-net}
    driver: ${GITLAB_NET_DRIVER:-overlay}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-minio-vol}
    driver: local
    driver_opts:
      type: ${VOL_TYPE:-nfs4}
      o: addr=${VOL_ADDR:-127.0.0.1},${VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${MINIO_VOL_DEVICE:-:/minio-vol/}
