version: '3.9'

services:
  minio:
    image: ${IMAGE_NAME:-minio/minio}:${IMAGE_TAG:-latest}
    command: server ${DATA_PATH} --address :${SERVER_PORT} --console-address :${CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
      MINIO_SERVER_URL: http://127.0.0.1:${SERVER_PORT}
      MINIO_BROWSER_REDIRECT_URL: https://${TRAEFIK_CONSOLE_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      MINIO_PROMETHEUS_URL:
      MINIO_PROMETHEUS_JOB_ID:
      MINIO_PROMETHEUS_AUTH_TYPE:
    networks:
      minio-net:
      traefik-net:
      metric-net:
    volumes:
      - data-vol:${DATA_PATH}
    healthcheck:
      test: curl --fail --silent http://127.0.0.1:${SERVER_PORT}/minio/health/live
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-5}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}

        traefik.http.routers.minio-server.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.minio-server.rule: Host(`${TRAEFIK_SERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.routers.minio-server.service: minio-server
        traefik.http.services.minio-server.loadbalancer.server.port: ${SERVER_PORT}

        traefik.http.routers.minio-console.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.minio-console.rule: Host(`${TRAEFIK_CONSOLE_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.routers.minio-console.service: minio-console
        traefik.http.services.minio-console.loadbalancer.server.port: ${CONSOLE_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-256M}

networks:
  minio-net:
    name: ${MINIO_NET_NAME:-minio-net}
    driver: ${MINIO_NET_DRIVER:-overlay}
    attachable: ${MINIO_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
