version: '3.5'

services:
  minio:
    image: ${IMAGE_NAME:-minio/minio}:${IMAGE_TAG:-latest}
    command: server ${DATA_PATH} --address :${SERVER_PORT} --console-address :${CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
      MINIO_SERVER_URL: http://localhost:${SERVER_PORT}
      MINIO_BROWSER_REDIRECT_URL: https://${TRAEFIK_CONSOLE_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      MINIO_PROMETHEUS_URL:
      MINIO_PROMETHEUS_AUTH_TYPE:
    networks:
      minio-net:
      traefik-net:
      gitlab-net:
      metric-net:
    volumes:
      - data-vol:${DATA_PATH}
    healthcheck:
      test: curl --fail --silent http://localhost:${SERVER_PORT}/minio/health/live
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-5}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.server.frontend.rule: Host:${TRAEFIK_SERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.console.frontend.rule: Host:${TRAEFIK_CONSOLE_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.server.backend: server
        traefik.console.backend: console
        traefik.server.port: '${SERVER_PORT}'
        traefik.console.port: '${CONSOLE_PORT}'
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  minio-net:
    name: ${MINIO_NET_NAME:-minio-net}
    driver: ${MINIO_NET_DRIVER:-overlay}
    attachable: ${MINIO_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  gitlab-net:
    name: ${GITLAB_NET_NAME:-gitlab-net}
    driver: ${GITLAB_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-minio-vol}
    driver: local
    driver_opts:
      type: ${VOL_TYPE:-nfs4}
      o: addr=${VOL_ADDR:-127.0.0.1},${VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${MINIO_VOL_DEVICE:-:/minio-vol/}
